# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-20 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField(verbose_name='电话号码')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('isActive', models.BooleanField(default=True, verbose_name='激活/禁用')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
